sudo: true
dist: trusty
env:
  global:
  - DOCKER_USERNAME=matthewberryman
  - secure: LnPcIvY9sPnaUVdAvitwGN+jVbSX76/4Xy1O1jwUhQ/NY2yXM1/jW/SAQ7sVi4zhsExRkW1PNrRBEKVYwo0TIhtfbHfXP1lOBwd9XTmjjBMAQqhtKJK98CMzrw9bNLhYXjibhN29BQa1aKwGvUGd7x/kmjkyK0irnkc0lwGhb9ytoCmPaigppIRTCfinhNF308m5MNP1S1QeK7huuhlhosPRd5oDoBHZ64bj4H4cjxqratses8W80+TOl+4XGvMs5kEcRooSZz+19UuZMZYz+rcxPC87lkJTLUEqaQ6vFpR6bUe0yENWXk0E0CE/9keCSGG4VLMTDz0/IPGpzzA6a2rwMdIZbM5TcFVS2IHBHRtUCbm3SGgVlATUQyWKQ9Lq+A4iGZozuRX3hamUsqGY3O9ouxfnpbAxAdvWhTWbqIQbn1mpbVy0zGLlV5jmXSTQsm0+8PM0+ndqotSGHPHBE9Akd4PoGe3D+UgSzBUbcEZBkKZfK0RdwnUBGSR6cJyK2D+XMQTFw/yXf3A0+1ce14HK0mduK0XkyXWBRzHcWiCUpggiOX4/c0vr/qfoxtACPvlssMHDxKwrwPZdvNSRT1rZJqFlUF35QcrZAWp72X+alNQdSuRnvM9EW5XpZLlraJ/MydoMLwRjS155Qrxd/g/HyVL68UjWDx9WOhFJ7uA=
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t $DOCKER_USERNAME/postgresql .
    - docker push $DOCKER_USERNAME/postgresql
