sudo: true
dist: trusty
env:
  global:
  - DOCKER_USERNAME=matthewberryman
  - secure: aAsxgRSITw+o4iDj35f/Cz/NqS0QpZFkfZk8VBir/C6V2oOEvNlpCvT652hFnG8cyYZu7hfqZPrCaIdbtcDEqzzCpRGambKuLY4HY8MUWfO1m78LRkrh3PTC/yZQMaOmaQu6DTdK9OKWo6UaRzbWSHva3o7yjoo9GHav4cQBQAiiK+H78My1RuXv0jXmivzq2JCReWyS5dm8wYnJcrH2z7i/QxZZP1oh8AFktIwd5XDN0w5iUMwfmEmfAkbUIuSBV0kMfb+QP2I6ir8S2NZhB1VCGnJcAUyTNIz+mRt46s5fsGgXo7wGeldurux4ENfSc0caoXiLBMpB8UsFhAMIQyMvyc4o1d3ta6wfIyek779ZN0IcDjAl88/srvIM6F3dHOwL0KWRH4zHQNZRis8dg5olWVNsP13xyoHVGVgnzxAxNvXE/BVuxavWxnHKtff4GOpKYpIGAWUZcbXcJTZjRvXhwdpiwCVjQO1V35lKecmJlPvx6pLzyr7weK2gLCZ0EjEMTT5qw4qZZNH3BsqrxZlyc7HUBYTpO0+nHMiLpMXhqR76gt75mKxk9x+CWcHBspedD6PNslXk1uGKbuhP+OkqRgmr6AYgYnf6YQ3UroHDhK+ivd2l1IWQgGbm/RA1Mjq8YAI5+dDHhTlZVKHMzIZPRrho28Vna9LIFxU1SoE=
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_USERNAME/postgresql .
    - docker push $DOCKER_USERNAME/postgresql
