sudo: true
dist: trusty
env:
  global:
  - DOCKER_USERNAME=matthewberryman
  - secure: BfeyJZUsh8l8nvCt7oar8uFTUmLemFBk6p0gAE5mj1WLe4eYAfYgfBeVdVi6IPNOLZLCjey2ptLtXhUE24D6ER0L91ANrsBWliTmXf08yb8hTf/08Fa6+rGLdsdHQW0rdeJgro0j9Zg3n29V97FzP8GcW5EJfNbnuUuO9weIMUfT9hsUcIEvm4PVEoy4IYk+JUbTDGrRIV9PaS+C5HBsWQHn1/FAmi+A3fq3QU0S00BMRWl2Qs4785o4ZKeN9lco+xg5IP+qpG9wGfk4KNPRBOhlL7rlAPQE9yI2xGay0FZDl4i4d1x3qiNrUY/Vuu6uD0tPTrWb0QIyW1dIWmM8FHWaQ1B68ag9XZx/S9FaGOi83M4ZG9wYcV698iraPXWwAIkkI+qp1+SI/mGVHZdMOE6rWNFrun0YDW38i6dw6Xnvqd5LbbDR04VeTSSTLOSwu4VoVxNtIZeVBLhqyxDtRv09rX1hMmXwiVUJtPUddvi+OW6734zRbXDJo1+q74DCQOZ25ZJ79KN0bnT0XqXZ4+QW8KxgOCoDQI1aX4ImrmN+5a0b//7+TAWW05v1G9cUO/u7SQc9ax4fwOstMoQscj9z4iMO0gUHdVXu/5j6c/ZrK2vJWAmQJI/rqOSqvUDWhUe6B3zsLXhB1vOq1atG5SgGxZeiEVuO8Dg0vm31ZOg=
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_USERNAME/postgresql .
    - docker push $DOCKER_USERNAME/postgresql
